apiVersion: v1
kind: Pod
metadata:
  name: busybox-test
  labels:
    security: S2
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - /bin/sh
    args: [-c, 'while true; do cat /dev/null > /logdir/access.log; sleep 10; done']
