apiVersion: v1
kind: Pod
metadata:
  name: busybox-guaranteed-high-1cpu
  labels:
    foo: bar
spec:
  priorityClassName: high-priority
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        foo: bar
  containers:
  - name: busybox
    image: busybox
    resources:
      requests:
        cpu: "1"
        memory: 200Mi
      limits:
        cpu: "1"
        memory: 200Mi
    command:
    - /bin/sh
    args: [-c, 'while true; do cat /dev/null > /logdir/access.log; sleep 10; done']
