kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: true
authorization:
  mode: "AlwaysAllow"
clusterDomain: "cluster.local"
clusterDNS:
  - "10.32.0.10"
#podCIDR: "10.21.0.0/16"
resolvConf: "/run/systemd/resolve/resolv.conf"
runtimeRequestTimeout: "15m"
#cgroupDriver: "systemd"
cgroupDriver: "cgroupfs"
