kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: "./ca.pem"
authorization:
  mode: Webhook
clusterDomain: "cluster.local"
clusterDNS:
  - "10.10.0.182"
#podCIDR: "10.21.0.0/16"
resolvConf: "/run/systemd/resolve/resolv.conf"
runtimeRequestTimeout: "15m"
#cgroupDriver: "systemd"
cgroupDriver: "cgroupfs"
tlsCertFile: "./alex-hp.pem"
tlsPrivateKeyFile: "./alex-hp-key.pem"
