apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-pod
  labels:
    app: hello-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-pod
  template:
    metadata:
      labels:
        app: hello-pod
      name: hello-pod
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/instance
                      operator: In
                      values:
                        - '{{ .Release.Name }}'
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
      - name: busybox
        image: busybox
        resources:
          requests:
            cpu: 1
          limits:
            cpu: 1
        command:
        - /bin/sh
        args: [-c, 'while true; do cat /dev/null > /logdir/access.log; sleep 10; done']
